version: '2'
services:
  db:
    image: postgres:9.4.1
    ports:
      - "9432:5432"

  app:
    build: .
    command: bin/rails server --port 3000 --binding 0.0.0.0
    ports:
      - "3000:3000"
    links:
      - db
      - selenium
    depends_on:
      - db
      - selenium
    environment:
      - DOCKER=true  

  selenium:
    image: selenium/standalone-chrome
